/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f9891a794a052f04cb3ee5deb68f9951)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	API: Fetcher /* civic-compass-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
