/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9d08edbf5a3679b284bec8a8504adfc4)
interface __BaseEnv_Env {
	PROFILES: KVNamespace;
	USER_PROFILES: KVNamespace;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
