/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2cb31d667112e69178046ca2d1918132)
interface __BaseEnv_Env {
	PROFILES: KVNamespace;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
